apiVersion: apps/v1
kind: Deployment
metadata:
  name: eas-server
  namespace: eas-self-hosting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eas-server
  template:
    metadata:
      labels:
        app: eas-server
    spec:
      containers:
      - name: eas-server
        image: expo/eas-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: eas-secrets
              key: JWT_SECRET
        - name: EXPO_API_KEY
          valueFrom:
            secretKeyRef:
              name: eas-secrets
              key: EXPO_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: eas-server
  namespace: eas-self-hosting
spec:
  selector:
    app: eas-server
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eas-worker
  namespace: eas-self-hosting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eas-worker
  template:
    metadata:
      labels:
        app: eas-worker
    spec:
      containers:
      - name: eas-worker
        image: expo/eas-server:latest
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: eas-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: eas-secrets
              key: JWT_SECRET
        - name: EXPO_API_KEY
          valueFrom:
            secretKeyRef:
              name: eas-secrets
              key: EXPO_API_KEY
        - name: WORKER_MODE
          value: "true"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

