apiVersion: v1
kind: Namespace
metadata:
  name: eas-self-hosting
  labels:
    name: eas-self-hosting
---
apiVersion: v1
kind: Secret
metadata:
  name: eas-secrets
  namespace: eas-self-hosting
type: Opaque
data:
  # Base64 encoded values - updated with secure generated values
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWp3dC1rZXktMjQ0NTA4MzQ4  # my-super-secret-jwt-key-244508348
  EXPO_API_KEY: ZXhwby1hcGkta2V5LTE2MjQ3NzI5NzA=       # expo-api-key-1624772970
  POSTGRES_PASSWORD: c2VjdXJlLXBvc3RncmVzLXBhc3N3b3JkLTgyMDgzMjgyNw==           # secure-postgres-password-820832827
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eas-config
  namespace: eas-self-hosting
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://eas_user:eas_password@postgres:5432/eas_db"
  REDIS_URL: "redis://redis:6379"
  POSTGRES_DB: "eas_db"
  POSTGRES_USER: "eas_user"

