apiVersion: v1
kind: Namespace
metadata:
  name: eas-self-hosting
  labels:
    name: eas-self-hosting
---
apiVersion: v1
kind: Secret
metadata:
  name: eas-secrets
  namespace: eas-self-hosting
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWhlcmU=  # your-jwt-secret-here
  EXPO_API_KEY: eW91ci1leHBvLWFwaS1rZXk=       # your-expo-api-key
  POSTGRES_PASSWORD: ZWFzX3Bhc3N3b3Jk           # eas_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eas-config
  namespace: eas-self-hosting
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://eas_user:eas_password@postgres:5432/eas_db"
  REDIS_URL: "redis://redis:6379"
  POSTGRES_DB: "eas_db"
  POSTGRES_USER: "eas_user"

